const locationsData = [
    {
        name: "The Mustard Seed",
        address: "7025 44 St SE, Calgary, AB T2C 4E8",
        phone: "403-723-9422",
        website: "https://theseed.ca",
        email: "info@theseed.ca",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 50.9930,
        lng: -113.9610
    },
    {
        name: "Calgary Drop-In & Rehab Centre",
        address: "3640 11A St NE, Calgary, AB",
        phone: "403-264-0856",
        website: "https://calgarydropin.ca",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 51.0824,
        lng: -114.0152
    },
    {
        name: "Calgary Food Bank",
        address: "5000 11 St SE, Calgary, AB T2H 2Y5",
        phone: "403-253-2050",
        website: "https://calgaryfoodbank.com",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 50.9995,
        lng: -114.0193
    },
    {
        name: "Calgary Humane Society",
        address: "4455 110 Ave SE, Calgary, AB T2C 2T7",
        phone: "403-205-4455",
        website: "https://www.calgaryhumane.ca",
        email: "",
        type: "animal-welfare",
        description: "A non-profit organization providing animal welfare services to the Calgary community.",
        lat: 50.9508,
        lng: -113.9334
    },
    {
        name: "Inn From The Cold",
        address: "110 11 Ave SE, Calgary, AB T2G 0X5",
        phone: "403-266-3600",
        website: "https://innfromthecold.org",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 51.0423,
        lng: -114.0597
    },
    {
        name: "Distress Centre Calgary / 211 Alberta",
        address: "Suite 500, 1010 8 Ave SW, Calgary, AB",
        phone: "211 or 403-266-4357",
        website: "https://ab.211.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services  to the Calgary community.",
        lat: 51.0454,
        lng: -114.0837
    },
    {
        name: "Momentum",
        address: "1010 8 Ave SW #300, Calgary, AB",
        phone: "403-272-9323",
        website: "https://momentum.org",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0454,
        lng: -114.0837
    },
    {
        name: "Calgary Women's Emergency Shelter",
        address: "500-1509 17 Ave SW, Calgary, AB",
        phone: "403-290-1552",
        website: "https://www.calgarywomensshelter.com",
        email: "",
        type: "womens-services",
        description: "A non-profit organization providing womens services services to the Calgary community.",
        lat: 51.0383,
        lng: -114.0963
    },
    {
        name: "Wood's Homes",
        address: "805 37 St NW, Calgary, AB",
        phone: "403-299-9699",
        website: "https://www.woodshomes.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0597,
        lng: -114.1417
    },
    {
        name: "Alpha House",
        address: "203 15 Ave SE, Calgary, AB",
        phone: "403-234-7388",
        website: "https://alphahousecalgary.com",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 51.0401,
        lng: -114.0565
    },
    {
        name: "Calgary John Howard Society",
        address: "910 7 Ave SW #300, Calgary, AB",
        phone: "403-265-4144",
        website: "https://www.calgaryjohnhoward.org",
        email: "",
        type: "legal-services",
        description: "A non-profit organization providing legal services services to the Calgary community.",
        lat: 51.0487,
        lng: -114.0820
    },
    {
        name: "Elizabeth Fry Society of Calgary",
        address: "1731 10 Ave SW, Calgary, AB",
        phone: "403-294-0737",
        website: "https://www.elizabethfrycalgary.ca",
        email: "",
        type: "legal-services",
        description: "A non-profit organization providing legal services services to the Calgary community.",
        lat: 51.0441,
        lng: -114.0999
    },
    {
        name: "CUPS (Calgary Urban Project Society)",
        address: "1001 10 Ave SW, Calgary, AB",
        phone: "403-221-8780",
        website: "https://www.cupscalgary.com",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0442,
        lng: -114.0837
    },
    {
        name: "The Alex Community Health Centre",
        address: "2840 2 Ave SE, Calgary, AB",
        phone: "403-520-2260",
        website: "https://www.thealex.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0503,
        lng: -113.9995
    },
    {
        name: "Accessible Housing Calgary",
        address: "200-802 3 Ave SW, Calgary, AB",
        phone: "403-282-1872",
        website: "https://accessiblehousing.ca",
        email: "",
        type: "housing-services",
        description: "A non-profit organization providing housing services services to the Calgary community.",
        lat: 51.0514,
        lng: -114.0805
    },
    {
        name: "Canadian Mental Health Association - Calgary Region",
        address: "#400, 105 12 Ave SE, Calgary, AB",
        phone: "403-297-1700",
        website: "https://cmha.calgary.ab.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Kids Cancer Care Foundation of Alberta",
        address: "5757 4 St SE, Calgary, AB",
        phone: "403-216-9210",
        website: "https://www.kidscancercare.ab.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 50.9888,
        lng: -114.0652
    },
    {
        name: "Ronald McDonald House Charities Alberta",
        address: "111 West Campus Place NW, Calgary, AB",
        phone: "403-240-3000",
        website: "https://rmhcalberta.org",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 51.0808,
        lng: -114.1423
    },
    {
        name: "Brown Bagging for Calgary's Kids",
        address: "909 11 Ave SW, Calgary, AB",
        phone: "403-264-7979",
        website: "https://bb4ck.org",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0435,
        lng: -114.0827
    },
    {
        name: "YWCA Calgary",
        address: "320 5 Ave SE, Calgary, AB",
        phone: "403-263-1550",
        website: "https://www.ywcalgary.ca",
        email: "",
        type: "womens-services",
        description: "A non-profit organization providing womens services services to the Calgary community.",
        lat: 51.0486,
        lng: -114.0531
    },
    {
        name: "Calgary Immigrant Women's Association",
        address: "200-138 4 Ave SE, Calgary, AB",
        phone: "403-263-4414",
        website: "https://www.ciwa-online.com",
        email: "",
        type: "womens-services",
        description: "A non-profit organization providing womens services services to the Calgary community.",
        lat: 51.0498,
        lng: -114.0583
    },
    {
        name: "Immigrant Services Calgary",
        address: "910 7 Ave SW #1200, Calgary, AB",
        phone: "403-265-1120",
        website: "https://www.immigrantservicescalgary.ca",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0487,
        lng: -114.0820
    },
    {
        name: "Centre for Newcomers",
        address: "125, 565 - 36 Street NE, Calgary, AB",
        phone: "403-569-3325",
        website: "https://www.centrefornewcomers.ca",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0561,
        lng: -113.9782
    },
    {
        name: "Calgary Catholic Immigration Society",
        address: "1111 11 Ave SW 5th Floor, Calgary, AB",
        phone: "403-262-2006",
        website: "https://www.ccisab.ca",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0436,
        lng: -114.0863
    },
    {
        name: "Calgary Bridge Foundation for Youth",
        address: "#205, 920 36 Street NE, Calgary, AB",
        phone: "403-230-7745",
        website: "https://www.cbfy.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0594,
        lng: -113.9782
    },
    {
        name: "Big Brothers Big Sisters of Calgary and Area",
        address: "5945 Centre St S, Calgary, AB",
        phone: "403-777-3535",
        website: "https://bbbscalgary.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 50.9875,
        lng: -114.0628
    },
    {
        name: "Boys & Girls Clubs of Calgary",
        address: "223 12 Ave SW, Calgary, AB",
        phone: "403-276-9981",
        website: "https://www.boysandgirlsclubsofcalgary.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0423,
        lng: -114.0673
    },
    {
        name: "Closer to Home Community Services",
        address: "3507 17 Ave SW, Calgary, AB",
        phone: "403-543-0550",
        website: "https://www.closertohome.com",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0384,
        lng: -114.1374
    },
    {
        name: "carya",
        address: "200, 1000 8 Ave SW, Calgary, AB",
        phone: "403-269-9888",
        website: "https://caryacalgary.ca",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0456,
        lng: -114.0838
    },
    {
        name: "Aspen Family & Community Network Society",
        address: "20, 2404 42 Ave SE, Calgary, AB",
        phone: "403-219-3477",
        website: "https://www.aspenfamily.org",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0068,
        lng: -114.0041
    },
    {
        name: "Further Education Society of Alberta",
        address: "130, 2121 29 Street NE, Calgary, AB",
        phone: "403-250-5034",
        website: "https://www.furthered.ca",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0700,
        lng: -113.9961
    },
    {
        name: "Calgary Public Library Foundation",
        address: "800 3 St SE, Calgary, AB",
        phone: "403-221-2002",
        website: "https://libraryfoundation.ca",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0452,
        lng: -114.0539
    },
    {
        name: "Calgary Arts Development",
        address: "1430, 225 8 Ave SW, Calgary, AB",
        phone: "403-264-5330",
        website: "https://calgaryartsdevelopment.com",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0461,
        lng: -114.0673
    },
    {
        name: "Propellus",
        address: "1177 11 Ave SW #300, Calgary, AB",
        phone: "403-265-5633",
        website: "https://www.propellus.org",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0435,
        lng: -114.0877
    },
    {
        name: "United Way of Calgary and Area",
        address: "600, 105 12 Ave SE, Calgary, AB",
        phone: "403-231-6265",
        website: "https://www.calgaryunitedway.org",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Calgary Foundation",
        address: "1180, 105 12 Ave SE, Calgary, AB",
        phone: "403-802-7700",
        website: "https://calgaryfoundation.org",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "The Poppy Fund / Calgary Veteran's Food Bank",
        address: "#1, 4539 – 6th Street N.E., Calgary, AB",
        phone: "403-265-6304",
        website: "https://www.calgarypoppyfund.com",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 51.0954,
        lng: -114.0396
    },
    {
        name: "Meals on Wheels",
        address: "5759 80 Ave SE, Calgary, AB",
        phone: "403-243-2834",
        website: "https://www.mealsonwheels.com",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 50.9892,
        lng: -113.9692
    },
    {
        name: "Kerby Centre",
        address: "1133 7 Ave SW, Calgary, AB",
        phone: "403-265-0661",
        website: "https://www.kerbycentre.com",
        email: "",
        type: "seniors-services",
        description: "A non-profit organization providing seniors services services to the Calgary community.",
        lat: 51.0488,
        lng: -114.0870
    },
    {
        name: "Operation Eyesight Universal",
        address: "#200, 4321 9 St SE, Calgary, AB",
        phone: "403-283-6323",
        website: "https://operationeyesight.com",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0061,
        lng: -114.0245
    },
    {
        name: "Wellspring Calgary",
        address: "1404 Home Rd NW, Calgary, AB",
        phone: "403-521-5292",
        website: "https://wellspringcalgary.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0660,
        lng: -114.1611
    },
    {
        name: "Canadian Red Cross - Southern Alberta Region",
        address: "1305 11 Ave SW, Calgary, AB",
        phone: "403-273-4426",
        website: "https://www.redcross.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0435,
        lng: -114.0906
    },
    {
        name: "Salvation Army - Community Services Calgary",
        address: "3823 34 St NE, Calgary, AB",
        phone: "403-410-1111",
        website: "https://salvationarmy.ca/alberta",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0847,
        lng: -113.9829
    },
    {
        name: "Habitat for Humanity Southern Alberta",
        address: "210, 805 Manning Rd NE, Calgary, AB",
        phone: "403-253-9331",
        website: "https://www.habitatsouthernab.ca",
        email: "",
        type: "housing-services",
        description: "A non-profit organization providing housing services services to the Calgary community.",
        lat: 51.0581,
        lng: -114.0305
    },
    {
        name: "Calgary Legal Guidance",
        address: "840 7 Ave SW #100, Calgary, AB",
        phone: "403-234-9266",
        website: "https://clg.ab.ca",
        email: "",
        type: "legal-services",
        description: "A non-profit organization providing legal services services to the Calgary community.",
        lat: 51.0489,
        lng: -114.0811
    },
    {
        name: "Pro Bono Law Alberta",
        address: "255 5 Ave SW #500, Calgary, AB",
        phone: "403-541-4803",
        website: "https://pbla.ca",
        email: "",
        type: "legal-services",
        description: "A non-profit organization providing legal services services to the Calgary community.",
        lat: 51.0490,
        lng: -114.0689
    },
    {
        name: "Student Legal Assistance",
        address: "Murray Fraser Hall, University of Calgary, 2500 University Dr NW, Calgary, AB",
        phone: "403-220-6637",
        website: "https://slacalgary.com",
        email: "",
        type: "legal-services",
        description: "A non-profit organization providing legal services services to the Calgary community.",
        lat: 51.0772,
        lng: -114.1306
    },
    {
        name: "Rise (formerly Enterprising Women)",
        address: "#100, 105 12 Ave SE, Calgary, AB",
        phone: "403-237-8858",
        website: "https://www.risecalgary.ca",
        email: "",
        type: "womens-services",
        description: "A non-profit organization providing womens services services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Servants Anonymous Society of Calgary",
        address: "1008 10 St SE, Calgary, AB",
        phone: "403-237-8477",
        website: "https://www.servantsanon.com",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0436,
        lng: -114.0396
    },
    {
        name: "HIV Community Link",
        address: "110 16a St NW, Calgary, AB",
        phone: "403-508-2500",
        website: "https://www.hivcl.org",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0537,
        lng: -114.0993
    },
    {
        name: "Calgary Sexual Health Centre",
        address: "#304, 301 14 St NW, Calgary, AB",
        phone: "403-283-5580",
        website: "https://www.calgarysexualhealth.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0543,
        lng: -114.0945
    },
    {
        name: "Calgary Counselling Centre",
        address: "#1000, 105 12 Ave SE, Calgary, AB",
        phone: "403-691-5991",
        website: "https://calgarycounselling.com",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Eastside Community Centre (operated by YMCA)",
        address: "1010 8 Ave SW, Calgary, AB",
        phone: "403-269-6701",
        website: "https://www.ymcacalgary.org/eastside",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0454,
        lng: -114.0837
    },
    {
        name: "Calgary Scope Society",
        address: "219 18 St SE, Calgary, AB",
        phone: "403-509-0200",
        website: "https://www.calgaryscope.org",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0494,
        lng: -114.0152
    },
    {
        name: "Calgary Quest School",
        address: "3405 37 St SW, Calgary, AB",
        phone: "403-253-0333",
        website: "https://www.questschool.ca",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0204,
        lng: -114.1437
    },
    {
        name: "Between Friends",
        address: "8989 Macleod Trail SW #205, Calgary, AB",
        phone: "403-269-9133",
        website: "https://betweenfriends.ab.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 50.9620,
        lng: -114.0682
    },
    {
        name: "Easter Seals Alberta",
        address: "103, 811 Manning Rd NE, Calgary, AB",
        phone: "403-235-5662",
        website: "https://www.easterseals.ab.ca",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0583,
        lng: -114.0305
    },
    {
        name: "Foothills Academy Society",
        address: "745 37 St NW, Calgary, AB",
        phone: "403-270-9400",
        website: "https://www.foothillsacademy.org",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0586,
        lng: -114.1417
    },
    {
        name: "CNIB Foundation (Calgary)",
        address: "10 11a St NE, Calgary, AB",
        phone: "403-266-8831",
        website: "https://cnib.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0515,
        lng: -114.0182
    },
    {
        name: "Deaf & Hear Alberta",
        address: "6323 10 St SE, Calgary, AB",
        phone: "403-284-6200",
        website: "https://www.deafandhearalberta.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 50.9840,
        lng: -114.0207
    },
    {
        name: "Cerebral Palsy Association in Alberta",
        address: "121, 3608 33 St NW, Calgary, AB",
        phone: "403-219-3603",
        website: "https://www.cpalberta.com",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0827,
        lng: -114.1332
    },
    {
        name: "Kidney Foundation of Canada - Southern Alberta",
        address: "6007 1a St SW, Calgary, AB",
        phone: "403-255-6108",
        website: "https://kidney.ca/southern-alberta",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 50.9865,
        lng: -114.0728
    },
    {
        name: "Heart & Stroke Foundation - Alberta",
        address: "119 14 St NW #100, Calgary, AB",
        phone: "403-264-5549",
        website: "https://www.heartandstroke.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0531,
        lng: -114.0945
    },
    {
        name: "Diabetes Canada - Calgary and District Branch",
        address: "220, 6223 2 St SE, Calgary, AB",
        phone: "403-266-0620",
        website: "https://www.diabetes.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 50.9847,
        lng: -114.0583
    },
    {
        name: "The Calgary Ability Network",
        address: "103, 811 Manning Rd NE, Calgary, AB",
        phone: "403-283-4200",
        website: "https://www.calgaryabilitynetwork.ca",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0583,
        lng: -114.0305
    },
    {
        name: "Calgary Newcomers Collaborative",
        address: "1111 11 Ave SW 5th Floor, Calgary, AB",
        phone: "403-262-2006",
        website: "https://www.calgarynewcomerscollaborative.ca",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0436,
        lng: -114.0863
    },
    {
        name: "Calgary Immigrant Educational Society",
        address: "1723 40 St SE, Calgary, AB",
        phone: "403-235-3666",
        website: "https://www.immigrant-education.ca",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0372,
        lng: -113.9723
    },
    {
        name: "Calgary Literacy Project (Calgary Reads)",
        address: "105, 105 12 Ave SE, Calgary, AB",
        phone: "403-686-9300",
        website: "https://www.calgaryreads.com",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Calgary Refugee Support",
        address: "125, 565 - 36 Street NE, Calgary, AB",
        phone: "403-569-3325",
        website: "https://www.centrefornewcomers.ca/refugeesupport",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0561,
        lng: -113.9782
    },
    {
        name: "Calgary Seniors' Resource Society",
        address: "3639 26 St NE, Calgary, AB T1Y 5E1",
        phone: "403-266-6200",
        website: "https://www.calgaryseniors.org",
        email: "",
        type: "seniors-services",
        description: "A non-profit organization providing seniors services services to the Calgary community.",
        lat: 51.0831,
        lng: -114.0003
    },
    {
        name: "Calgary Youth Services Network",
        address: "203 15 Ave SE, Calgary, AB",
        phone: "403-234-7388",
        website: "https://www.alphahousecalgary.com",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0401,
        lng: -114.0565
    },
    {
        name: "Calgary Volunteer Centre (Propellus)",
        address: "1177 11 Ave SW #300, Calgary, AB",
        phone: "403-265-5633",
        website: "https://www.volunteercalgary.ab.ca",
        email: "",
        type: "employment-services",
        description: "A non-profit organization providing employment services services to the Calgary community.",
        lat: 51.0435,
        lng: -114.0877
    },
    {
        name: "Calgary Animal Rescue Society (CARES)",
        address: "Bay G, 3400 48 Ave NE, Calgary, AB",
        phone: "403-269-2273",
        website: "https://www.caas.ca",
        email: "",
        type: "animal-welfare",
        description: "A non-profit organization providing animal welfare services to the Calgary community.",
        lat: 51.0963,
        lng: -113.9575
    },
    {
        name: "Calgary Music Education Foundation",
        address: "200-138 4 Ave SE, Calgary, AB",
        phone: "403-263-4414",
        website: "https://www.calgarymusic.ca",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0498,
        lng: -114.0583
    },
    {
        name: "Calgary Arts & Culture Alliance",
        address: "1430, 225 8 Ave SW, Calgary, AB",
        phone: "403-264-5330",
        website: "https://calgaryartsdevelopment.com",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0461,
        lng: -114.0673
    },
    {
        name: "Calgary Environmental Action (Green Calgary)",
        address: "205, 223 12 Ave SW, Calgary, AB",
        phone: "403-230-1443",
        website: "https://www.greencalgary.org",
        email: "",
        type: "environment",
        description: "A non-profit organization providing environment services to the Calgary community.",
        lat: 51.0423,
        lng: -114.0673
    },
    {
        name: "Calgary Heritage Foundation",
        address: "1001 10 Ave SW, Calgary, AB",
        phone: "403-221-8780",
        website: "https://www.cupscalgary.com",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0442,
        lng: -114.0837
    },
    {
        name: "Calgary Historical Society",
        address: "PO Box 420, Stn G, Calgary, AB T3A 2A3",
        phone: "403-261-3662",
        website: "https://www.calgaryhistoricalsociety.ca",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Health Foundation",
        address: "800, 11012 Macleod Trail SE, Calgary, AB",
        phone: "403-943-0615",
        website: "https://www.calgaryhealthfoundation.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 50.9450,
        lng: -114.0682
    },
    {
        name: "Calgary Community Health Trust",
        address: "#400, 105 12 Ave SE, Calgary, AB",
        phone: "403-297-1700",
        website: "https://cmha.calgary.ab.ca",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Calgary Sports for Youth (KidSport Calgary)",
        address: "1828 24 St SW, Calgary, AB",
        phone: "403-202-0251",
        website: "https://kidsportcanada.ca/alberta/calgary/",
        email: "",
        type: "sports-recreation",
        description: "A non-profit organization providing sports recreation services to the Calgary community.",
        lat: 51.0371,
        lng: -114.1165
    },
    {
        name: "Calgary Bike Playgrounds",
        address: "200, 1000 8 Ave SW, Calgary, AB",
        phone: "403-269-9888",
        website: "https://caryacalgary.ca",
        email: "",
        type: "sports-recreation",
        description: "A non-profit organization providing sports recreation services to the Calgary community.",
        lat: 51.0456,
        lng: -114.0838
    },
    {
        name: "Calgary Parks Foundation",
        address: "225 13 Ave SW, Calgary, AB",
        phone: "403-974-0751",
        website: "https://www.parksfdn.com",
        email: "",
        type: "environment",
        description: "A non-profit organization providing environment services to the Calgary community.",
        lat: 51.0415,
        lng: -114.0673
    },
    {
        name: "Calgary Conservation Society",
        address: "2500 University Dr NW, Calgary, AB",
        phone: "403-266-5051",
        website: "https://www.ucalgary.ca/contact",
        email: "",
        type: "environment",
        description: "A non-profit organization providing environment services to the Calgary community.",
        lat: 51.0762,
        lng: -114.1299
    },
    {
        name: "Calgary Theatre for Young People",
        address: "200, 1000 8 Ave SW, Calgary, AB",
        phone: "403-264-8575",
        website: "https://caryacalgary.ca",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0456,
        lng: -114.0838
    },
    {
        name: "Calgary Youth Orchestra Society",
        address: "203 15 Ave SE, Calgary, AB",
        phone: "403-234-7388",
        website: "https://www.calgaryyouthorchestra.com",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0401,
        lng: -114.0565
    },
    {
        name: "Calgary Opera Association",
        address: "1315 7 St SW, Calgary, AB",
        phone: "403-262-7286",
        website: "https://calgaryopera.com",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0417,
        lng: -114.0789
    },
    {
        name: "Calgary Film Society (Calgary Cinematheque)",
        address: "Suite 118, 8820 48 Street NW, Calgary, AB",
        phone: "403-283-1490",
        website: "https://www.calgarycinema.org/",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.1009,
        lng: -114.1565
    },
    {
        name: "Calgary Learning Society (Calgary Learns)",
        address: "130, 2121 29 Street NE, Calgary, AB",
        phone: "403-250-5034",
        website: "https://www.calgarylearns.com",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0700,
        lng: -113.9961
    },
    {
        name: "Calgary STEM Outreach (University of Calgary)",
        address: "2500 University Dr NW, Calgary, AB",
        phone: "403-220-5555",
        website: "https://www.ucalgary.ca/future-students/undergraduate/outreach",
        email: "",
        type: "education",
        description: "A non-profit organization providing education services to the Calgary community.",
        lat: 51.0762,
        lng: -114.1299
    },
    {
        name: "Calgary Youth Empowerment Society",
        address: "200, 1000 8 Ave SW, Calgary, AB",
        phone: "403-269-9888",
        website: "https://caryacalgary.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0456,
        lng: -114.0838
    },
    {
        name: "Calgary Volunteer Lawyers (Calgary Legal Guidance)",
        address: "840 7 Ave SW #100, Calgary, AB",
        phone: "403-234-9266",
        website: "https://clg.ab.ca",
        email: "",
        type: "legal-services",
        description: "A non-profit organization providing legal services services to the Calgary community.",
        lat: 51.0489,
        lng: -114.0811
    },
    {
        name: "Calgary Community Food Bank Partner Org",
        address: "5000 11 St SE, Calgary, AB T2H 2Y5",
        phone: "403-253-2050",
        website: "https://www.calgaryfoodbank.com/partners",
        email: "",
        type: "food-shelter",
        description: "A non-profit organization providing food shelter services to the Calgary community.",
        lat: 50.9995,
        lng: -114.0193
    },
    {
        name: "Calgary Housing Support Services",
        address: "200-802 3 Ave SW, Calgary, AB",
        phone: "403-282-1872",
        website: "https://accessiblehousing.ca",
        email: "",
        type: "housing-services",
        description: "A non-profit organization providing housing services services to the Calgary community.",
        lat: 51.0514,
        lng: -114.0805
    },
    {
        name: "Calgary Addiction Recovery Services (Alpha House)",
        address: "203 15 Ave SE, Calgary, AB",
        phone: "403-234-7388",
        website: "https://alphahousecalgary.com",
        email: "",
        type: "health-services",
        description: "A non-profit organization providing health services services to the Calgary community.",
        lat: 51.0401,
        lng: -114.0565
    },
    {
        name: "Calgary Family Resource Network (Closer to Home)",
        address: "3507 17 Ave SW, Calgary, AB",
        phone: "403-543-0550",
        website: "https://www.closertohome.com",
        email: "",
        type: "community-support",
        description: "A non-profit organization providing community support services to the Calgary community.",
        lat: 51.0384,
        lng: -114.1374
    },
    {
        name: "Calgary Child Advocacy Centre",
        address: "400, 105 12 Ave SE, Calgary, AB",
        phone: "403-428-5300",
        website: "https://www.calgarycac.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 51.0421,
        lng: -114.0605
    },
    {
        name: "Calgary Men’s Resource Centre (Wood's Homes)",
        address: "805 37 St NW, Calgary, AB",
        phone: "403-299-9699",
        website: "https://www.woodshomes.ca",
        email: "",
        type: "mens-services",
        description: "A non-profit organization providing mens services services to the Calgary community.",
        lat: 51.0597,
        lng: -114.1417
    },
    {
        name: "Calgary Women’s Resource Centre (YWCA)",
        address: "320 5 Ave SE, Calgary, AB",
        phone: "403-263-1550",
        website: "https://www.ywcalgary.ca",
        email: "",
        type: "womens-services",
        description: "A non-profit organization providing womens services services to the Calgary community.",
        lat: 51.0486,
        lng: -114.0531
    },
    {
        name: "Calgary Refugee Sponsorship Council",
        address: "1111 11 Ave SW 5th Floor, Calgary, AB",
        phone: "403-262-2006",
        website: "https://www.ccisab.ca",
        email: "",
        type: "newcomer-services",
        description: "A non-profit organization providing newcomer services services to the Calgary community.",
        lat: 51.0436,
        lng: -114.0863
    },
    {
        name: "Calgary Employment Service (Immigrant Services Calgary)",
        address: "910 7 Ave SW #1200, Calgary, AB",
        phone: "403-265-1120",
        website: "https://www.immigrantservicescalgary.ca",
        email: "",
        type: "employment-services",
        description: "A non-profit organization providing employment services services to the Calgary community.",
        lat: 51.0487,
        lng: -114.0820
    },
    {
        name: "Calgary Youth Mentoring Network (Big Brothers Big Sisters)",
        address: "5945 Centre St S, Calgary, AB",
        phone: "403-777-3535",
        website: "https://bbbscalgary.ca",
        email: "",
        type: "youth-services",
        description: "A non-profit organization providing youth services services to the Calgary community.",
        lat: 50.9875,
        lng: -114.0628
    },
    {
        name: "Calgary Sports Development (Boys & Girls Clubs)",
        address: "223 12 Ave SW, Calgary, AB",
        phone: "403-276-9981",
        website: "https://www.boysandgirlsclubsofcalgary.ca",
        email: "",
        type: "sports-recreation",
        description: "A non-profit organization providing sports recreation services to the Calgary community.",
        lat: 51.0423,
        lng: -114.0673
    },
    {
        name: "Calgary Cultural Society",
        address: "1430, 225 8 Ave SW, Calgary, AB",
        phone: "403-264-5330",
        website: "https://calgaryartsdevelopment.com",
        email: "",
        type: "arts-culture",
        description: "A non-profit organization providing arts culture services to the Calgary community.",
        lat: 51.0461,
        lng: -114.0673
    },
    {
        name: "Carya",
        address: "5000 Bowness Road NW
Calgary, AB
T3B 0B9",
        phone: "403-269-9888",
        website: "https://caryacalgary.ca",
        email: "",
        type: "seniors-services",
        description: "A social impact organization providing mental health as well as family services to the Calgary community.",
        lat: 51.0456,
        lng: -114.0838
    },
    {
        name: "Calgary Community Gardens Association (Green Calgary)",
        address: "#810 105 12 Ave SE, Calgary, AB T2G 1A1",
        phone: "+13688878675",
        website: "https://www.greencalgary.org/about",
        email: "",
        type: "environment",
        description: "An urban environmental charity helping canadians live a more sustainable life through environmental action.",
        lat: 51.0423,
        lng: -114.0673
    },
    {
        name: "Centre For Newcomers",
        address: "125, 565 - 36 Street NE, Calgary, AB",
        phone: "403-569-3325",
        website: "https://www.centrefornewcomers.ca",
        email: "",
        type: "newcomer-services",
        description: "A social profit organization providing newcomer and immigrant services to the Calgary community.",
        lat: 51.0561,
        lng: -113.9782
    }
];
