// data
const locationsData = [
    {
        name: "Calgary Centre for Men and Families",
        address: "Unit 5, 3828 Parkhill Street SW Calgary, Alberta, T2S 2Z6",
        phone: "587-885-2839",
        website: "https://www.ccmfalberta.ca",
        email: "calgary@ccmfalberta.ca",
        type: "community-support",
        description: "The Canadian centre for men and families offers various supports to men to help navigate various situations.",
        lat: 51.0189,
        lng: -114.0935
    },
    {
        name: "Alberta Cancer Foundation (Calgary region)",
        address: "Unit 300, 1620 29 St NW, Calgary, AB T2N 4L7",
        phone: "866-412-4222",
        website: "https://albertacancer.ca",
        email: "acfonline@albertacancer.ca",
        type: "health",
        description: "The Alberta Cancer Foundation helps empower individuals and invests in cancer research.",
        lat: 51.0655,
        lng: -114.1270
    },
    {
        name: "Calgary Arts Development",
        address: "The Edison, 150 9 Ave SW #1410, Calgary, AB T2P 3H9",
        phone: "(403) 264-5330",
        website: "https://calgaryartsdevelopment.com",
        email: "info@calgaryartsdevelopment.com",
        type: "arts-culture",
        description: "An organization that is committed to Indigenous reconciliation, racial equity, disability justice, and gender and sexual diversity.",
        lat: 51.0449,
        lng: -114.0654
    },
    {
        name: "Calgary Society of Independent Filmmakers",
        address: "The Edison Suite 1410 (14th floor) 150 9th Ave. SW Calgary, AB T2P 3H9",
        phone: "403-264-5330",
        website: "https://calgaryartsdevelopment.com/news-information/directory/calgary-society-of-independent-filmmakers/",
        email: "info@calgaryartsdevelopment.com",
        type: "arts-culture",
        description: "A non-profit based organization that supports filmmakers and story tellers.",
        lat: 51.0449,
        lng: -114.0654
    },
    {
        name: "Calgary Allied Arts Foundation",
        address: "Suite #435 – 1721 29th Ave SW, Calgary, AB T2T 6T7",
        phone: "",
        website: "https://www.calgaryalliedartsfoundation.ca",
        email: "caafresidency@gmail.com",
        type: "arts-culture",
        description: "A non-profit organization that promotes visual arts in Calgary.",
        lat: 51.0287,
        lng: -114.1030
    },
    {
        name: "Calgary Climate Hub",
        address: "PO Box 22126, RPO Bankers Hall, Calgary, AB T2P 4J5, Canada",
        phone: "",
        website: "https://www.calgaryclimatehub.ca",
        email: "https://www.calgaryclimatehub.ca/contact",
        type: "environment",
        description: "An organization that educates, empowers and advocates for grassroots climate action.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Animal Rescue Society",
        address: "No Central Location",
        phone: "403-816-0759",
        website: "https://calgaryanimalrescue.com",
        email: "info@calgaryanimalrescue.com",
        type: "animal-welfare",
        description: "A foster based rescue that aims to find loving homes for cats and dogs.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Youth Orchestra Society",
        address: "Mount Royal University Conservatory, 4825 Mount Royal Gate SW, Calgary, AB T3E 6K6",
        phone: "403-440-5978",
        website: "https://www.calgaryyouthorchestra.org/about.html",
        email: "cyo@mtroyal.ca",
        type: "arts-culture",
        description: "A flagship ensemble of the Mont Royal University Conservatory, it provides educational and cultural experiences to young musicians.",
        lat: 51.0125,
        lng: -114.1130
    },
    {
        name: "Historical Society of Alberta",
        address: "",
        phone: "",
        website: "https://maps.app.goo.gl/4hm7f48VZjsAFDJj7,403-261-3662,https://albertahistory.org/,An",
        email: "info@albertahistory.org",
        type: "arts-culture",
        description: "organization that advocates for Alberta's history through partnerships and various chapters.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Opera Association",
        address: "1315 7 STREET SW, CALGARY, AB",
        phone: "403-262-7286",
        website: "https://www.calgaryopera.com/",
        email: "INFO@CALGARYOPERA.COM",
        type: "arts-culture",
        description: "Built to serve the community and help foster Canadian talent through Opera and educational training.",
        lat: 51.0413,
        lng: -114.0788
    },
    {
        name: "Alberta Music Education Foundation",
        address: "Percy Page Centre 11759 Groat Rd NW Edmonton, AB T5M 3K6",
        phone: "780-409-8407",
        website: "https://www.amef.ca/about_us.php",
        email: "info@amef.ca",
        type: "education",
        description: "A registered charity that provides funding for music education through programs.",
        lat: 53.5489,
        lng: -113.5480
    },
    {
        name: "Distress Centre Calgary",
        address: "999 8 St SW #500 Calgary, AB T2R 1J5",
        phone: "403-266-4357",
        website: "https://distresscentre.com",
        email: "info@distresscentre.com",
        type: "mental-health",
        description: "Distress Centre Calgary provides 24-hour crisis support, professional counselling, youth peer support, and navigation and referrals through 211 and Coordinated Entry.",
        lat: 51.0444,
        lng: -114.0810
    },
    {
        name: "Calgary Bridge Foundation for Youth",
        address: "910 7 Ave SW #1500, Calgary, AB T2P 3N8",
        phone: "(403) 230-7745",
        website: "https://cbfy.ca",
        email: "contactus@cbfy.ca",
        type: "newcomer-services",
        description: "The Calgary’s Bridge Foundation for Youth (CBFY) supports immigrant and refugee youth and their families with knowledge and information about Canadian culture and schooling system.",
        lat: 51.0470,
        lng: -114.0825
    },
    {
        name: "Brown Bagging for Calgary's Kids",
        address: "909 11 Ave SW #110, Calgary, AB T2R 1L8",
        phone: "(403) 264-7979",
        website: "https://www.brownbagging.org",
        email: "info@bb4ck.org",
        type: "food-security",
        description: "Brown Bagging for Calgary’s Kids (BB4CK) is a community-funded, non-profit organization that has been working for over 30 years to make sure kids across Calgary have access to the food they need.",
        lat: 51.0434,
        lng: -114.0825
    },
    {
        name: "Youth Central",
        address: "820, 105 – 12 Ave SE, Calgary AB T2G 1A1",
        phone: "403-266-5448",
        website: "https://youthcentral.com",
        email: "info@youthcentral.com",
        type: "child-family-services",
        description: "Empower youth to participate in their communities through various activities.",
        lat: 51.0423,
        lng: -114.0612
    },
    {
        name: "Calgary Public Library Foundation",
        address: "800 3 St SE, Calgary, AB T2G 2E7",
        phone: "(403) 221-2002",
        website: "http://libraryfoundation.ca",
        email: "info@libraryfoundation.ca",
        type: "education",
        description: "To connect and inspire donors to support Calgary Public Library’s innovative and enhanced programs and services beyond their core funding.",
        lat: 51.0453,
        lng: -114.0580
    },
    {
        name: "Carya",
        address: "800 – 1000 7 Ave SW Calgary, Alberta, T2P 5L5",
        phone: "403-269-9888",
        website: "https://caryacalgary.ca",
        email: "",
        type: "community-support",
        description: "A social impact organization helping families and communities in Calgary.",
        lat: 51.0469,
        lng: -114.0838
    },
    {
        name: "YCC - Youth Centres of Calgary (Ogden)",
        address: "7400 23 St SE, Calgary, AB T2C 0X9",
        phone: "(403) 850-7884",
        website: "http://www.youthcentresofcalgary.com",
        email: "info@youthcentresofcalgary.com",
        type: "child-family-services",
        description: "Since 2018, YCC has provided vulnerable youth ages 8-15 in Calgary's underserved neighborhoods with a safe, welcoming, and empowering 'home away from home.' From our cozy, community based centres in Ogden and Forest Lawn, we offer free after-school and summer programs designed to meet kids' most essential needs:\n\n* Caring relationships with mentors who truly show up\n* Nutritious meals\n* A safe place to be a kid — to play, to create, to belong\n\nPrograms include art and music, sports coaching, technology access, reading spaces, gardening, and real life mentorship. Every day, we help kids build resilience, confidence, and joy. IT’S SIMPLE – BUT IT’S POWERFUL.",
        lat: 50.9867,
        lng: -114.0029
    },
    {
        name: "The Mustard Seed",
        address: "7025 44 St SE, Calgary, AB T2C 4E8",
        phone: "403-723-9422",
        website: "https://theseed.ca",
        email: "info@theseed.ca",
        type: "food-shelter",
        description: "The Mustard Seed is a non-profit organization that has been caring for individuals experiencing homelessness and poverty.",
        lat: 50.9930,
        lng: -113.9610
    },
    {
        name: "Meals On Wheels Calgary",
        address: "5759-80 Avenue SE Calgary, Alberta T2C 4S6",
        phone: "(403) 243-2834",
        website: "https://www.mealsonwheels.com",
        email: "info@mealsonwheels.com",
        type: "food-security",
        description: "Calgary, Meals on Wheels provides nutritious affordable meals to those facing food insecurity.",
        lat: 50.9997,
        lng: -113.9213
    },
    {
        name: "Calgary Women's Shelter Society",
        address: "500-1509 Centre St SW Calgary AB T2G 2E6",
        phone: "403-290-1552",
        website: "https://www.calgarywomensshelter.com",
        email: "info@fearisnotlove.ca",
        type: "food-shelter",
        description: "The Calgary Women's Emergency Centre helps to end family violence and provide a safe community to individuals.",
        lat: 51.0402,
        lng: -114.0700
    },
    {
        name: "The Calgary Food Bank",
        address: "5000 11 Street SE Calgary, AB T2H 2Y5",
        phone: "403-253-2059",
        website: "https://www.calgaryfoodbank.com",
        email: "info@calgaryfoodbank.com",
        type: "food-security",
        description: "A first line of emergency food support for individuals facing food insecurity in Calgary.",
        lat: 51.0089,
        lng: -114.0200
    },
    {
        name: "Calgary Dream Centre",
        address: "4510 Macleod Trl SW, Calgary, AB T2G 0A4",
        phone: "(403) 243-5598",
        website: "https://calgarydreamcentre.com",
        email: "info@calgarydreamcentre.com",
        type: "community-support",
        description: "Calgary Dream Centre provides innovative recovery programs, affordable housing, and a supportive community to people who have lost hope along the way.",
        lat: 51.0145,
        lng: -114.0720
    },
    {
        name: "Salvation Army Calgary - Community Services",
        address: "420 9 Ave SE Calgary, AB T2G 0R9",
        phone: "(403) 410-1111",
        website: "https://www.salvationarmycalgary.org",
        email: "CSCalgary.Info@salvationarmy.ca",
        type: "community-support",
        description: "An organization that helps give hope, and meet human needs.",
        lat: 51.0447,
        lng: -114.0538
    },
    {
        name: "Freshstart Recovery Centre",
        address: "411 41 Ave NE Calgary, AB T2E 2N4",
        phone: "(403) 387-6266",
        website: "https://freshstartrecovery.ca",
        email: "info@freshstartrecovery.ca",
        type: "health",
        description: "A community based organization that provides recovery support across Alberta.",
        lat: 51.0886,
        lng: -114.0537
    },
    {
        name: "Habitat for Humanity Southern Alberta",
        address: "4009 8 St NE, Calgary, AB",
        phone: "403-276-6011",
        website: "https://habitatsouthernab.ca",
        email: "events@habitatsouthernab.ca",
        type: "food-shelter",
        description: "An organization that partners with local families to make affordable homeownership a reality. Together, we build stability, create new opportunities, and help families plan for a stronger future.",
        lat: 51.0877,
        lng: -114.0300
    },
    {
        name: "Women's Centre of Calgary",
        address: "39 - 4 Street NE, Calgary, Alberta T2E 3R6",
        phone: "(403) 264-1155",
        website: "https://www.womenscentrecalgary.org",
        email: "info@womenscentrecalgary.org",
        type: "community-support",
        description: "A local organization that offers various supports to women in Calgary.",
        lat: 51.0505,
        lng: -114.0470
    },
    {
        name: "Drop-In & Rehab Centre Society",
        address: "3640 11A St NE, Calgary, AB",
        phone: "403-264-0856",
        website: "https://calgarydropin.ca",
        email: "",
        type: "food-shelter",
        description: "Help individuals facing homelessness, and offer various care services.",
        lat: 51.0847,
        lng: -114.0178
    },
    {
        name: "Calgary Seniors' Resource",
        address: "3639 26th St NE, Calgary AB T1Y 5E1",
        phone: "(403) 266-6200",
        website: "https://calgaryseniors.org",
        email: "info@calgaryseniors.org",
        type: "community-support",
        description: "An organization committed to help and care for seniors in our community.",
        lat: 51.0850,
        lng: -113.9960
    },
    {
        name: "Stem Innovation Academy",
        address: "3636 Research Road NW Calgary, AB T2L 1Y1",
        phone: "597-943-2499",
        website: "https://steminnovationacademy.com",
        email: "nwjh@stemia.ca",
        type: "education",
        description: "STEM Innovation Academy is a free public charter school for grades 7-12 in Calgary with a special focus on hands-on Science, Technology, Engineering and Math (STEM) learning.",
        lat: 51.0850,
        lng: -114.1378
    },
    {
        name: "The Calgary Flames Sports Bank",
        address: "3557 52nd Street SE Calgary, Alberta T2B 3R3",
        phone: "403-202-0251",
        website: "https://www.flamessportsbank.ca",
        email: "admin@flamessportsbank.ca",
        type: "sports-recreation",
        description: "Provides free gently used sports equipment to children who qualify for the program.",
        lat: 51.0210,
        lng: -113.9430
    },
    {
        name: "Sports Development Foundation",
        address: "3270, 4310 104 Avenue Northeast, Calgary, AB, Canada",
        phone: "",
        website: "https://sdfoundation.ca/",
        email: "Support@SDFoundation.ca",
        type: "sports-recreation",
        description: "A non-profit organization helping young athletes by providing mentorship, funding and scholarships.",
        lat: 51.1343,
        lng: -113.9395
    },
    {
        name: "Alberta Adolescent Recovery Centre (Calgary)",
        address: "303 Forge Rd SE, Calgary, AB T2H 0S9",
        phone: "(403) 253-5250",
        website: "https://www.aarc.ab.ca",
        email: "info@aarc.ab.ca",
        type: "health",
        description: "An organization that helps individuals facing addiction.",
        lat: 51.0000,
        lng: -114.0310
    },
    {
        name: "Calgary Learning Institute",
        address: "2616 18 Street NE Suite 201 Calgary, AB T2E 7R1 Canada",
        phone: "1-403-285-3555",
        website: "https://calgarylearning.com",
        email: "info@calgarylearning.com",
        type: "education",
        description: "The Calgary Learning Institutes goal is to eliminate poverty through education by offering individualized training programs in English, adult workplace training, computer skills and tutoring to help students and adults gain the skills and confidence to be successful.",
        lat: 51.0760,
        lng: -114.0040
    },
    {
        name: "Trellis Society - Housing Support",
        address: "2609 15 St NE, Calgary, AB T2E 8Y2",
        phone: "403-219-3477",
        website: "https://www.growwithtrellis.ca/locations",
        email: "donations@growwithtrellis.ca",
        type: "food-shelter",
        description: "An organization committed to serving the community and individuals across generations.",
        lat: 51.0758,
        lng: -114.0118
    },
    {
        name: "United Way Calgary and Area",
        address: "240-1000 8 Ave SW, Calgary, AB",
        phone: "403-802-7700",
        website: "https://calgaryunitedway.org/",
        email: "uway@calgaryunitedway.org",
        type: "community-support",
        description: "An organization that supports at-risk individuals.",
        lat: 51.0457,
        lng: -114.0839
    },
    {
        name: "Calgary Humane Society",
        address: "2200 16 Ave NE, Calgary, AB T2E 1J8",
        phone: "403-205-4455",
        website: "https://www.calgaryhumane.ca",
        email: "general.inquiries@calgaryhumane.ca",
        type: "animal-welfare",
        description: "The Calgary Humane society is a animal welfare organization that provides various types of assistance to animals.",
        lat: 51.0645,
        lng: -114.0139
    },
    {
        name: "Inn From The Cold",
        address: "200-998 11 Ave SW, Calgary, AB",
        phone: "403-266-3600",
        website: "https://innfromthecold.org",
        email: "media@innfromthecold.org",
        type: "food-shelter",
        description: "Provides support for homelessness in Calgary.",
        lat: 51.0433,
        lng: -114.0833
    },
    {
        name: "Calgary Theatre for Young People",
        address: "2007 10 AVE SW, Calgary, AB T3C 0K4",
        phone: "587-392-5832",
        website: "https://cypt.ca/contact/",
        email: "",
        type: "arts-culture",
        description: "Provide development opportunities to children in performing arts through camps and workshops.",
        lat: 51.0441,
        lng: -114.1100
    },
    {
        name: "North Central Family Resource Network",
        address: "200, 1725 10 Avenue SW Calgary, AB T3C 0K1",
        phone: "403-543-0550",
        website: "https://closertohome.com/north-central-family-resource-network/",
        email: "reception@closertohome.com",
        type: "child-family-services",
        description: "A charity that provides various services aimed at children and families.",
        lat: 51.0441,
        lng: -114.1030
    },
    {
        name: "Closer to Home Commmunity Services",
        address: "1725 10 Ave SW #200, Calgary, AB T3C 0K1",
        phone: "(403) 543-0550",
        website: "https://closertohome.com/",
        email: "reception@closertohome.com",
        type: "child-family-services",
        description: "A charitable foundation that works towards creating positive relationships for children, families and communities.",
        lat: 51.0441,
        lng: -114.1030
    },
    {
        name: "YWCA Calgary",
        address: "1715 17 Ave SE, Calgary, AB T2G 5J1",
        phone: "(403) 263-1550",
        website: "https://ywcacalgary.ca",
        email: "communications@ywcalgary.ca",
        type: "community-support",
        description: "Prevention, intervention, empowerment and leadership for the benefit of women and their families.",
        lat: 51.0378,
        lng: -114.0080
    },
    {
        name: "Centre for sexuality",
        address: "1509 Centre St S, Calgary, AB T2G 2E6",
        phone: "(403) 283-5580",
        website: "https://www.centreforsexuality.ca",
        email: "info@centreforsexuality.ca",
        type: "health",
        description: "Centre for Sexuality is a community-based organization delivering programs & services to support healthy sexuality across the lifespan.",
        lat: 51.0402,
        lng: -114.0700
    },
    {
        name: "Calgary Health Foundation",
        address: "1500-333 11 Ave SW Calgary, AB T2R 1L9",
        phone: "403-800-4200",
        website: "https://www.calgaryhealthfoundation.ca",
        email: "fundraising@calgaryhealthfoundation.ca",
        type: "health",
        description: "A community based charity raising funds to help advance heathcare in Calgary.",
        lat: 51.0430,
        lng: -114.0690
    },
    {
        name: "Calgary Immigrant Women's Association",
        address: "138 4 Ave SE, Calgary, AB T2G 4Z6",
        phone: "(403) 263-4414",
        website: "https://ciwa-online.com",
        email: "reception@ciwa-online.com",
        type: "newcomer-services",
        description: "Canadian Immigrant Women’s Association (CIWA) is a non-profit organization settlement agency that recognizes, responds to, and focuses on the unique concerns and needs of immigrant and refugee women, girls, and their families.",
        lat: 51.0485,
        lng: -114.0601
    },
    {
        name: "Alex Community Health Centre (The Alex)",
        address: "1212 4 St NW, Calgary, AB",
        phone: "403-245-3900",
        website: "https://www.thealex.ca",
        email: "info@thealex.ca",
        type: "health",
        description: "To improve quality of life through accessible and integrated health, housing and social services.",
        lat: 51.0610,
        lng: -114.0700
    },
    {
        name: "Calgary Wildlife",
        address: "11555-85th Street NW, Calgary, AB T3R 1J3",
        phone: "403-266-2282",
        website: "https://www.calgarywildlife.org/",
        email: "admin@calgarywildlife.org",
        type: "animal-welfare",
        description: "A nonprofit established to provide care for wildlife rehabilitation and to rescue injured or orphaned wildlife.",
        lat: 51.1510,
        lng: -114.2250
    },
    {
        name: "Calgary Catholic Immigration Society",
        address: "1111 11 Ave SW, Calgary, AB T2R 0G5",
        phone: "(403) 262-2006",
        website: "https://ccisab.ca",
        email: "contact@ccisab.ca",
        type: "newcomer-services",
        description: "In partnership, we empower immigrants and refugees to successfully settle and integrate in our communities.",
        lat: 51.0433,
        lng: -114.0872
    },
    {
        name: "Sponsorship of Refugees Program",
        address: "1111 - 11 Avenue SW Calgary, Alberta T2R 0G5 Canada",
        phone: "403-262-2006",
        website: "https://ccisab.ca/sponsorship-of-refugees-program/",
        email: "contact@ccisab.ca",
        type: "newcomer-services",
        description: "An organization that helps immigrants and newcomers to successfully settle and integrate into our communities.",
        lat: 51.0433,
        lng: -114.0872
    },
    {
        name: "Calgary Reads",
        address: "105 12 Ave SE, Calgary, AB T2G 1A1",
        phone: "(403) 777-8254",
        website: "https://calgaryreads.com",
        email: "",
        type: "education",
        description: "An organization that helps provide literacy support across calgary.",
        lat: 51.0423,
        lng: -114.0612
    },
    {
        name: "Canadian Mental Health Association (local)",
        address: "1040 7 Ave SW #105, Calgary, AB T2P 3G9",
        phone: "(403) 297-1700",
        website: "https://cmha.calgary.ab.ca",
        email: "info@cmha.calgary.ab.ca",
        type: "mental-health",
        description: "The Canadian Mental Health Association provides support for individuals with mental health concerns.",
        lat: 51.0470,
        lng: -114.0850
    },
    {
        name: "Momentum (formerly Calgary Neighborhoods)",
        address: "1010 8 Ave SW #300, Calgary, AB",
        phone: "403-244-9788",
        website: "https://momentum.org",
        email: "welcome@momentum.org",
        type: "community-support",
        description: "An organization that supports individuals in various situations.",
        lat: 51.0457,
        lng: -114.0839
    },
    {
        name: "Big Brothers Big Sisters of Calgary and Area",
        address: "1010 8 Ave SW #300, Calgary, AB",
        phone: "403-283-4144",
        website: "https://bigbrothersbigsisters.ca/",
        email: "calgary.comunucations@bigbrothersbigsisters.ca",
        type: "child-family-services",
        description: "An organization that supports youth and provides mentorship services.",
        lat: 51.0457,
        lng: -114.0839
    },
    {
        name: "Calgary Legal Guidance",
        address: "100, 840 – 7th Avenue SW Calgary, AB T2P 3G2",
        phone: "(403) 234-9266",
        website: "https://www.clg.ab.ca",
        email: "clg@clg.ab.ca",
        type: "legal-services",
        description: "A non-profit legal organization that helps provides free legal assistance to calgarians.",
        lat: 51.0475,
        lng: -114.0810
    },
    {
        name: "Momentum",
        address: "100, 525 28 St SE, Calgary AB, T2A 6W9",
        phone: "403-272-9323",
        website: "https://momentum.org",
        email: "welcome@momentum.org",
        type: "community-support",
        description: "We're here to support you, whether you're building your small business, your career, or your financial wellness.",
        lat: 51.0473,
        lng: -113.9930
    },
    {
        name: "Calgary Drop-In Centre (The DI)",
        address: "1 Dermot Baldwin Way SE Calgary T2G 0P8",
        phone: "403-263-5707",
        website: "https://calgarydropin.ca",
        email: "community@thedi.ca",
        type: "food-shelter",
        description: "At the Calgary Drop-In Centre, we welcome adults at risk of or experiencing homelessness.",
        lat: 51.0470,
        lng: -114.0480
    },
    {
        name: "Calgary Youth Justice Society",
        address: "#900, 620 7th Avenue S.W. Calgary, AB T2P 0Y8",
        phone: "(403) 261-9861",
        website: "https://calgaryyouthjustice.com",
        email: "jmallett@cyjs.ca",
        type: "legal-services",
        description: "An organization that connects adult volunteers in a positive way with young people who are facing challenges in their lives, some who are already involved with the criminal justice system.",
        lat: 51.0480,
        lng: -114.0760
    },
    {
        name: "Green Calgary",
        address: "#810 105 12 Ave SE, Calgary, AB T2G 1A1",
        phone: "1-368-887-8675",
        website: "https://www.greencalgary.org/about",
        email: "products@greencalgary.org",
        type: "environment",
        description: "An urban environmental charity helping calgarians live a sustainable life and take environmental action.",
        lat: 51.0423,
        lng: -114.0612
    },
    {
        name: "Family Services of Calgary",
        address: "#3404 25th Street N.E T1Y 6C1",
        phone: "403-205-5178",
        website: "https://familiesmatter.ca",
        email: "info@familiesmatter.ca",
        type: "child-family-services",
        description: "Help strengthen families through learnering opportunities.",
        lat: 51.0829,
        lng: -113.9990
    },
    {
        name: "Calgary Heritage Housing Foundation",
        address: "#3, 4303 – 14 Street NE Calgary, Alberta T2E 7A9",
        phone: "403-286-7402",
        website: "https://calgaryheritagehousing.ca/foundation/",
        email: "https://calgaryheritagehousing.ca/contact/",
        type: "food-shelter",
        description: "Committed to providing housing security to seniors at affordable rates.",
        lat: 51.0900,
        lng: -114.0130
    },
    {
        name: "Calgary Career Hub",
        address: "#130-75 Crowfoot Rise NW Calgary, AB T3G 4P5",
        phone: "403-201-4122",
        website: "https://www.calgarycareerhub.com",
        email: "",
        type: "employment",
        description: "A social impact organization helping job seekers find jobs in Calgary.",
        lat: 51.1278,
        lng: -114.1895
    },
    {
        name: "Centre for Newcomers",
        address: "#125 565 - 36 Street NE (Main Office, North side) Calgary, AB - T2A 6K3",
        phone: "403-569-3325",
        website: "https://www.centrefornewcomers.ca",
        email: "",
        type: "newcomer-services",
        description: "A social profit organization supporting immigrants and refugees in Calgary.",
        lat: 51.0558,
        lng: -113.9800
    },
    {
        name: "Calgary Public Library Foundation",
        address: "Central Library in downtown Calgary",
        phone: "403-221-2002",
        website: "https://libraryfoundation.ca",
        email: "info@libraryfoundation.ca",
        type: "education",
        description: "An organization that supports Calgary public library's programs and services.",
        lat: 51.0453,
        lng: -114.0580
    },
    {
        name: "Luna Child & Youth Advocacy Centre",
        address: "400, 3820 24 Avenue Northwest, Calgary, AB T3B 2X9",
        phone: "(403) 428-5300",
        website: "https://www.lunacentre.ca",
        email: "reception@lunacentre.ca",
        type: "child-family-services",
        description: "The Luna child and advocacy centre helps to support children and families impacted by child abuse.",
        lat: 51.0850,
        lng: -114.1390
    },
    {
        name: "ShelterBox Canada (Calgary connections)",
        address: "",
        phone: "647-352-1930",
        website: "https://shelterboxcanada.org",
        email: "support@shelterboxcanada.org",
        type: "community-support",
        description: "ShelterBox exists to ensure no one is without shelter after disaster.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Women's Emergency Shelter",
        address: "",
        phone: "",
        website: "https://ywcacalgary.ca/services/domestic-violence",
        email: "",
        type: "food-shelter",
        description: "The Calgary Homlessness Foundation allocates resources to frontline agencies that support individuals facing homelessness.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Homeless Foundation",
        address: "",
        phone: "",
        website: "https://www.calgaryhomeless.com",
        email: "",
        type: "food-shelter",
        description: "An organization that helps to support poverty and hunger in Calgary.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Community Kitchen Program",
        address: "",
        phone: "",
        website: "https://www.ckpcalgary.ca/",
        email: "",
        type: "food-security",
        description: "An organization that helps to support poverty and hunger in Calgary.",
        lat: null,
        lng: null
    },
    {
        name: "Calgary Allied Arts Foundation",
        address: "",
        phone: "",
        website: "https://www.calgaryalliedartsfoundation.ca/",
        email: "",
        type: "arts-culture",
        description: "A not-for-profit organization that help promote art and culture.",
        lat: null,
        lng: null
    },
    {
        name: "YCC - Youth Centres of Calgary (Forest Lawn)",
        address: "2620 40 St SE, Calgary, AB T2B 1C2",
        phone: "(403) 850-7884",
        website: "http://www.youthcentresofcalgary.com",
        email: "info@youthcentresofcalgary.com",
        type: "child-family-services",
        description: "Since 2018, YCC has provided vulnerable youth ages 8-15 in Calgary's underserved neighborhoods with a safe, welcoming, and empowering 'home away from home.' From our cozy, community based centres in Ogden and Forest Lawn, we offer free after-school and summer programs designed to meet kids' most essential needs:\n\n* Caring relationships with mentors who truly show up\n* Nutritious meals\n* A safe place to be a kid — to play, to create, to belong\n\nPrograms include art and music, sports coaching, technology access, reading spaces, gardening, and real life mentorship. Every day, we help kids build resilience, confidence, and joy. IT’S SIMPLE – BUT IT’S POWERFUL.",
        lat: 51.0308,
        lng: -113.9753
    },
];
